# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    avinor.baseurl: http://flydata.avinor.no/

services:
  guzzle.avinor.client:
    class: GuzzleHttp\Client
    arguments: [base_uri: %avinor.baseurl%]